services:
  fastapi:
    build: .
    container_name: archive_fastapi
    volumes:
      - /home/hilandjy/video_storage:/app/video_storage
    ports:
      - "2456:2456"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: archive_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    expose:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
