version: "3.9"

services:
  backend:
    build: .
    container_name: archive-backend
    ports:
      - "2456:2456"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    restart: always

  redis:
    image: redis:7
    container_name: archive-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
